-   name: "Install php{{ php_version }}-fpm"
    become: yes
    apt: pkg="php{{ php_version }}-fpm" state=latest
        
-   name: Use FPM
    command: /bin/true
    notify:
        - use FPM
  
-   name: Setup php.ini
    become: yes
    lineinfile: dest="/etc/php/{{ php_version }}/fpm/conf.d/99-overrides.ini"
                regexp="{{ item.reg }}"
                line="{{ item.line }}"
                create=yes

    with_items: '{{ php_ini_settings }}'

-   name: Install Apache fcgid
    become: yes
    apt: pkg=libapache2-mod-fcgid state=latest
  
-   name: Enable needed apache mods
    apache2_module: name={{ item }} state=present
    become: yes
    with_items:
        - proxy
        - proxy_fcgi
        - fcgid
    
-   name: Setup php-fpm config
    when: enviroment == 'dev'
    become: yes
    lineinfile: dest="/etc/php/{{ php_version }}/fpm/php-fpm.conf"
            create=no
            regexp="{{ item.reg }}"
            line="{{ item.line }}"
    with_items:
        - { reg: 'user = ', line: "user = {{ user }}"}
        
-   name: Setup default pool
    when: enviroment == 'dev'
    become: yes
    lineinfile: dest="/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
            create=no
            regexp="{{ item.reg }}"
            line="{{ item.line }}"
    with_items:
        - { reg: 'listen.owner = ', line: 'listen.owner = {{ user }}'}
        - { reg: 'listen.group = ', line: 'listen.group = {{ user }}'}
        - { reg: 'user = ', line: "user = {{ user }}"}
        - { reg: 'group = ', line: 'group = {{ user }}'}

